# Computational Methods in Economics

## Problem Set - Solving Systems of Linear Equations: Suggested Solutions

In [1]:
# Author: Alex Schmitt (schmitt@ifo.de), Christina Littlejohn (littlejohn@ifo.de)

import datetime
print('Last update: ' + str(datetime.datetime.today()))

Last update: 2017-12-04 19:24:07.876947


### Preliminaries

#### Import Modules

In [2]:
import numpy as np
import scipy.optimize

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn

import numpy as np
import scipy.optimize
import scipy.linalg


# import sys
from importlib import reload

## Question 1 (A)

(a) Find the largest positive integer $n$ such that $2^n - 1$ is a DP number.

(b) Show that the distance between two adjacent DP numbers $y_1$ and $y_2$ with $y_1 < y_2$ that, 

\begin{equation}
   | y_2 - y_1 | = \epsilon_{DP} 2^{e(y_1) - 1023}. 
\end{equation}

Hint: Consider two cases for $e$ and $f$ that make two DP numbers adjacent.


## Question 2 (N)

Write a function **backward_sub** that implements the backward-substitution algorithm to solve an upper triangular system of equations in Python. As a first step, derive an expression for $x_i$, analogous to the case of forward-substitution in the lecture.

In [3]:
def backward_sub(A, b):
    """
    Implements the backward-substitution algorithm to solve an upper triangular system of equations
    
    For doctest:
    
    >>> backward_sub( np.array([[1, 1], [0, 1]]), np.array([2, 1])  )
    array([ 1.,  1.])
    
    >>> backward_sub( np.array([[1, 2, 3], [0, 5, 7], [0, 0, 9]]), np.array([1, 2, 3])  )
    array([ 0.13333333, -0.06666667,  0.33333333])
    
     
    """
    ## check input: is A a square matrix?
    n, m = A.shape
    assert n == m, "A must be a square matrix"
    
    ## initialize solution vector
    x = np.zeros(n)
    
    ## fill solution vector using a for loop
    for i in range(n):
        
        ## compute sum on numerator of recursive rule
        summ = 0
        for j in range(i):
            summ += A[(n-1)-i, (n-1)-j] * x[(n-1)-j]
        
        ## use rule; NB: start at the last element in x!
        x[(n-1)-i] = (b[(n-1)-i] - summ) / A[(n-1)-i, (n-1)-i]
        
    return x        

In [4]:
## alternative: use vector multiplication for sum (instead of inner loop)

def backward_sub2(A, b):
    """
    Implements the backward-substitution algorithm to solve an upper triangular system of equations
    
    For doctest:
    
    >>> backward_sub( np.array([[1, 1], [0, 1]]), np.array([2, 1])  )
    array([ 1.,  1.])
    
    >>> backward_sub( np.array([[1, 2, 3], [0, 5, 7], [0, 0, 9]]), np.array([1, 2, 3])  )
    array([ 0.13333333, -0.06666667,  0.33333333])
    
    
    """
    ## check input: is A a square matrix?
    n, m = A.shape
    assert n == m, "A must be a square matrix"
    
    ## initialize solution vector
    x = np.zeros(n)
    
    ## fill solution vector using a for loop
    for i in range(n):
        
        ## compute sum on numerator of recursive rule 
        summ = A[(n-1)-i, (n-1) - (i-1):] @ x[(n-1) - (i-1):]
        
        ## use rule; NB: start at the last element in x!
        x[(n-1)-i] = (b[(n-1)-i] - summ) / A[(n-1)-i, (n-1)-i]
        
    return x
        

In [5]:
## test case
A = np.array([[1, 2, 3],
              [0, 5, 7],
              [0, 0, 9]])

b = np.array([1, 2, 3])

In [6]:
backward_sub(A, b)

array([ 0.13333333, -0.06666667,  0.33333333])

In [7]:
backward_sub2(A, b)

array([ 0.13333333, -0.06666667,  0.33333333])

In [8]:
## check our result
np.linalg.solve(A, b)

array([ 0.13333333, -0.06666667,  0.33333333])

In [9]:
## Alternative: use doctest
import doctest
doctest.testmod()

TestResults(failed=0, attempted=4)

## Question 3 (A)

In Miranda & Fackler, p. 11, you find an example for Gaussian elimination, specifically for the matrix:

In [10]:
A = np.array([[2, 0, -1, 2],
              [4, 2, -1, 4],
              [2, -2, -2, 3],
              [-2, 2, 7, -3]])

In their implementation of LU factorization (which is difference from ours!) they find

In [11]:
pl = np.array([[1, 0, 0, 0],
              [2, 1, 0, 0],
              [1, -1, 0, 1],
              [-1, 1, 1, 0]])
u = np.array([[2, 0, -1, 2],
              [0, 2, 1, 0],
              [0, 0, 5, -1],
              [0, 0, 0, 1]])

It is easy to verify that this is a valid LU factorization:

In [12]:
np.allclose(pl @ u, A)

True

Using Scipy's **linalg.lu** function, we get different matrices for **pl** and **u**:

In [13]:
pl, u = scipy.linalg.lu(A, permute_l=True)
print( np.allclose(pl @ u, A) )
pl, u

True


(array([[  5.00000000e-01,   3.33333333e-01,  -5.55111512e-18,
           1.00000000e+00],
        [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  5.00000000e-01,   1.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [ -5.00000000e-01,  -1.00000000e+00,   1.00000000e+00,
           0.00000000e+00]]),
 array([[ 4.        ,  2.        , -1.        ,  4.        ],
        [ 0.        , -3.        , -1.5       ,  1.        ],
        [ 0.        ,  0.        ,  5.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , -0.33333333]]))

In [14]:
P = np.array([[0, 1, 0 , 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1],
              [1, 0, 0, 0]])

Q = np.array([[1, 0, 0, 0],
             [0.5, 1, 0, 0],
             [-0.5, -1, 1, 0],
             [0.5, 1/3, 0, 1]])

(np.linalg.inv(P) @ Q) @ u

array([[ 2.,  0., -1.,  2.],
       [ 4.,  2., -1.,  4.],
       [ 2., -2., -2.,  3.],
       [-2.,  2.,  7., -3.]])

One important takeaway from this is that there multiple ways to factor a matrix into LU components, and hence multiple valid LU representations. Use our PA = LU factorization algorithm from the lecture on matrix $A$, i.e. find $pl$ and $u$ analytically.

## Question 4 (N)

Solve Exercise 2.2 in Miranda and Fackler. That is, find the solution to a SLE with

In [15]:
A = np.array([[54, 14, -11, 2], 
              [14, 50, -4, 29],
              [-11, -4, 55, 22],
              [2, 29, 22, 95]]
            )
b = np.array([1, 1, 1, 1])

numerically, using
a) LU factorization,
b) Gauss-Jacobi,
c) Gauss-Seidel.

For LU factorization, do not use the **linalg.solve** functions in Numpy or Scipy. However, you can use Scipy's **linalg.lu** function.

In [16]:
np.linalg.solve(A, b)

array([ 0.01893441,  0.01680508,  0.02335523, -0.00041085])

#### (a) LU Factorization

In [17]:
def forward_sub(A, b):
    """
    Implements the forward-substitution algorithm to solve a lower triangular system of equations
    """
    n, m = A.shape
    
    assert n == m, "A must be a square matrix"
    
    x = np.zeros(n)
    
    for i in range(n):
        
        summ = 0
        for j in range(i):
            summ += A[i, j] * x[j]
        
        x[i] = (b[i] - summ) / A[i, i]   
    
    return x

In [18]:
%%timeit -n1 -r1
P, L, U = scipy.linalg.lu(A)
y = forward_sub(L, b)
x = backward_sub(U, y)
print(x)


[ 0.01893441  0.01680508  0.02335523 -0.00041085]
1 loop, best of 1: 2.08 ms per loop


#### (b) Gauss-Jacobi

In [19]:
def gauss_jacobi(A, b, x0):
    """ 
    Implements the Gauss-Seidel method with a over-relaxation parameter
    """
    eps = 1
    tol = 1e-8
    it = 0
    maxit = 100

    x = x0
    Q = np.diag(np.diag(A))
    Q_inv = np.linalg.inv(Q)
    
    while eps > tol and it < maxit:
        it += 1 
        x_new = Q_inv @ b + ( np.eye(len(b)) - Q_inv @ A) @ x
        eps = np.linalg.norm(x_new - x)
        x = x_new
        
        
    return x, it 

In [20]:
%%timeit -n1 -r1
x0 = np.zeros(4)
gauss_jacobi(A, b, x0)
x, it = gauss_jacobi(A, b, x0)
print('Number of iterations = {}'.format(it))
print(x)

Number of iterations = 25
[ 0.01893441  0.01680507  0.02335523 -0.00041085]
1 loop, best of 1: 6.81 ms per loop


#### (c) Gauss-Seidel 

In [21]:
def gauss_seidel(A, b, x0):
    """ 
    Implements the Gauss-Seidel method with a over-relaxation parameter
    """
    eps = 1
    tol = 1e-8
    it = 0
    maxit = 100

    x = x0
    Q = np.triu(A)
    Q_inv = np.linalg.inv(Q)
    
    while eps > tol and it < maxit:
        it += 1 
        x_new = Q_inv @ b + ( np.eye(len(b)) - Q_inv @ A) @ x
        eps = np.linalg.norm(x_new - x)
        x = x_new
        
    return x, it  

In [22]:
%%timeit -n1 -r1
x0 = np.zeros(4)
gauss_seidel(A, b, x0) 
x, it = gauss_seidel(A, b, x0)
print('Number of iterations = {}'.format(it))
print(x)

Number of iterations = 14
[ 0.01893441  0.01680508  0.02335523 -0.00041085]
1 loop, best of 1: 5.77 ms per loop


## Question 5 (A)

Show that the relativ absolute difference between a real number $z$ and the DP number closest to it, $z_{DP}$, is bounded above by halt machine epsilon, i.e.
\begin{equation}
   \left| \frac{z_{DP} - z}{z} \right| \le \frac{1}{2} \epsilon_{DP}.
\end{equation}

Hint: Use what you have showed in question 1, namely that
\begin{equation}
   | y_2 - y_1 | = \epsilon_{DP} 2^{e(y_1) - 1023}, 
\end{equation}
where $y_1$ and $y_2$ are DP numbers.

## Question 6 (N)


From Judd (1998), chapter 3. Suppose that demand for good $i$ is 

\begin{equation}
    d_i(p) = a_i \sum_{j \neq i} p_j - b_ip_i + c_i,\ \ i = 1, ..., n
\end{equation}

where $a_i > b_i > 0$, and that supply is 

\begin{equation}
    s_i(p) = A_i + B_i p_i, \ \ i = 1, ..., n 
\end{equation}

where $B_i > 0$. Write a program to solve for equilibrium with sensible choices of $a_i$, $b_i$, $A_i$ and $B_i$. That means read in the parameters, check that they are consistent with commonsense economics (downward sloping demand curves, increasing supply curves and concave utility) and output the equilibrium prices and outputs. Your code should work for any number $n \ge 1$.

In [23]:
def find_eq(a,b,c,A,B):
    """ 
    Takes in the parameters for a, b, c, A, B as flat numpy arrays. Solves for equilibrium
    price and quantity vectors given sensible choices of a_i, b_i, A_i, B_i.
    
    Returns the price and quantity vectors as two flat numpy arrays.
    """
    
    # get length of the array
    m, = b.shape
    
    # check that b > 0 and a > b
    assert b.min() > 0,    'All values in b must be greater than 0'
        
    for i in range(m):    
        if a[i] < b[i]:
            print('At position {} the a !> b'.format(i))
        else: continue
            
    # check that B > 0 
    assert B.min() > 0,    'All values in B must be greater than 0'
    
    # create matrix M populated with values from (-b_i - B_i) and a
    M = np.zeros((m,m))
    for i in range(m):
        for j in range(m):
            if i == j:
                M[i,j] = -b[i] - B[i]
            else:
                M[i,j] = a[i]
          
    # create array x with values A_i - c_i
    x = A - c
 
    # use gaussian to compute p vector
    p0 = np.zeros(m)
    p, it = gauss_jacobi(M, x, p0)
    
    # compute q vector with A + B*p
    q = A + (B * p)
    
    return p, q

In [24]:
a = np.array([.3,.4,.4,1,.8])
b = np.array([.2,.2,.3,.4,.5])
c = np.array([1,1,1,1,1])
A = np.array([-5,-4,-5,6,7])
B = np.array([5,6,1,8,7])


p_eq, q_eq = find_eq(a,b,c,A,B)
print('p_eq = ', p_eq) 
print('q_eq = ', q_eq)

p_eq =  [ 1.5942729   1.31686888  5.70078507  0.44982303  0.16658665]
q_eq =  [ 2.97136451  3.90121328  0.70078507  9.59858428  8.16610657]


#### Addendum: LU Factorization

*Directly from Miranda & Fackler (p.10 -12)*

Note that the following is an implementation of LU factorization that is an *alternative* to PA=LU factorization as presented in the lecture!

The L-U factors of a matrix *A* are computed using Gaussian elimination. The Gaussian elimination algorithm begins with matrices *L* and *U* initialized as *L = I* and *U = A*, where **I** is the identity matrix. The algorithm uses elementary row operations (interchanging rows and subtracting a constant multiple of one row from another) to transform *U* into an **upper triangular matrix**, while preserving the **permuted lower diagonality** of *L* and the factorization *A = LU*.

\begin{equation}A =
\left[
\begin{array}{ccccc}
    2 & 0 & -1 & 2 \\
    4 & 2 & -1 & 4 \\
    2 & -2 & -2 & 3 \\
    -2 & 2 & 7 & -3
\end{array}
\right]\end{equation}

The first stage of Gaussian elimination is intended to nullify the subdiagonal entries of the **first column** of the *U* matrix. The *U* matrix is updated by subtracting 2 times the first row from the second, subtraction 1 times the first row from the third, and subtraction -1 times the first row from the fourth. The *L* matrix, which initially equals the identity, is updated by **storing the multipliers** 2, 1, -1 as the subdiagonal entries of its first column. These operations yield:

\begin{equation}L =
\left[
\begin{array}{ccccc}
    1 & 0 & 0 & 0 \\
    2 & 1 & 0 & 0 \\
    1 & 0 & 1 & 0 \\
   -1 & 0 & 0 & 1
\end{array}
\right]
, U =
\left[
\begin{array}{ccccc}
    2 & 0 & -1 & 2 \\
    0 & 2 & 1 & 0 \\
    0 & -2 & -1 & 1 \\
    0 & 2 & 6 & -1
\end{array}
\right]\end{equation}



After the first stage of Gaussian elimination, *A = LU*, we see that *L* is lower triangular, but *U* is not yet upper triangular.
The second stage of Gaussian elimination is intended to nullify the subdiagonal entries of the **second column** of the *U* matrix. The *U* matrix is updated by subtracting -1 times the second row from the third and subtracting 1 times the second row from the fourth. The *L* matrix is updated by **storing the multipliers** -1 and 1 as the subdiagonal elements of its second column. These operations yield:

\begin{equation}L =
\left[
\begin{array}{ccccc}
    1 & 0 & 0 & 0 \\
    2 & 1 & 0 & 0 \\
    1 & -1 & 1 & 0 \\
   -1 & 1 & 0 & 1
\end{array}
\right]
, U =
\left[
\begin{array}{ccccc}
    2 & 0 & -1 & 2 \\
    0 & 2 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
    0 & 0 & 5 & -1
\end{array}
\right]\end{equation}

After the second stage of Gaussian elimination, *A = LU*, *L* is lower triangular, but *U* is still not upper triangular. In this case, there is a quick fix. Interchanging the third and fourth **rows** of *U*! The *L* matrix is then updated by interchanging the multipliers in the third and fourth **columns**. 

\begin{equation}L =
\left[
\begin{array}{ccccc}
    1 & 0 & 0 & 0 \\
    2 & 1 & 0 & 0 \\
    1 & -1 & 0 & 1 \\
   -1 & 1 & 1 & 0
\end{array}
\right]
, U =
\left[
\begin{array}{ccccc}
    2 & 0 & -1 & 2 \\
    0 & 2 & 1 & 0 \\
    0 & 0 & 5 & -1 \\
    0 & 0 & 0 & 1
\end{array}
\right]\end{equation}

This example terminates with a row-permuted lower triangular matrix, *L*. (Meaning by interchanging the third and fourth rows, we have a lower triangular matrix.)